apiVersion: v1
kind: Namespace
metadata:
  name: kimsawsome
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vnf
  namespace: kimsawsome
  labels:
    app: vnf
    vm.kubevirt.io/template: rhel9-desktop-medium
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: vnf
    spec:
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        memory:
          guest: 2Gi
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
      networks:
        - name: default
          pod: {}
      volumes:
        - name: rootdisk
          dataVolume:
            name: vnf-rootdisk
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              user: cloud-user
              ssh_authorized_keys: []
  dataVolumeTemplates:
    - metadata:
        name: vnf-rootdisk
      spec:
        storage:
          resources:
            requests:
              storage: 30Gi
        sourceRef:
          kind: DataSource
          name: rhel9
          namespace: openshift-virtualization-os-images