{{- if and .Values.operators.keycloakOperator.enabled .Values.operators.keycloakOperator.config.groups }}
{{- range .Values.operators.keycloakOperator.config.groups }}
{{- if .namespace }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keycloak-group-{{ .name }}
  namespace: {{ .namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .role }}
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: {{ .name }}
{{- else }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: keycloak-group-{{ .name }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .clusterRole }}
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: {{ .name }}
{{- end }}
{{- end }}
{{- end }}
